('getJson fileName = ', './json/bjtq.json')
[2017-10-11 16:36:56,911] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/wuh/work/myGit/myPro/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wuh/work/myGit/myPro/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wuh/work/myGit/myPro/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wuh/work/myGit/myPro/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wuh/work/myGit/myPro/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "test.py", line 21, in hello_world
    return JsonUtil.getBjtq()
  File "./testFile.py", line 19, in getBjtq
    return self.__getJson(BJ_TQ)
  File "./testFile.py", line 13, in __getJson
    fileJson = open(fileName,'r+')
IOError: [Errno 2] No such file or directory: './json/bjtq.json'
[pid: 8143|app: 0|req: 4/5] 10.75.109.117 () {50 vars in 847 bytes} [Wed Oct 11 16:36:56 2017] GET / => generated 291 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.15 (64bit) on [Wed Oct 11 16:37:50 2017] ***
compiled with version: 4.8.5 on 10 October 2017 18:13:19
os: Linux-4.4.0-96-generic #119~14.04.1-Ubuntu SMP Wed Sep 13 08:40:48 UTC 2017
nodename: wuh
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/wuh/work/myGit/myPro
detected binary path: /home/wuh/work/myGit/myPro/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/wuh/work/myGit/myPro/app/
your processes number limit is 63767
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 2.7.6 (default, Oct 26 2016, 20:33:43)  [GCC 4.8.4]
Set PythonHome to /home/wuh/work/myGit/myPro/venv/
Python main interpreter initialized at 0x211a630
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 702080 bytes (685 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
__init__ is call
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x211a630 pid: 8364 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8364)
spawned uWSGI worker 1 (pid: 8367, cores: 2)
spawned uWSGI worker 2 (pid: 8368, cores: 2)
spawned uWSGI worker 3 (pid: 8369, cores: 2)
spawned uWSGI worker 4 (pid: 8372, cores: 2)
('getJson fileName = ', './json/bjtq.json')
[2017-10-11 16:37:55,226] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/wuh/work/myGit/myPro/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wuh/work/myGit/myPro/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wuh/work/myGit/myPro/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/wuh/work/myGit/myPro/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wuh/work/myGit/myPro/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "test.py", line 21, in hello_world
    return JsonUtil.getBjtq()
  File "./testFile.py", line 19, in getBjtq
    return self.__getJson(BJ_TQ)
  File "./testFile.py", line 13, in __getJson
    fileJson = open(fileName,'r+')
IOError: [Errno 2] No such file or directory: './json/bjtq.json'
[pid: 8369|app: 0|req: 1/1] 10.75.109.117 () {50 vars in 847 bytes} [Wed Oct 11 16:37:55 2017] GET / => generated 291 bytes in 3 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
Wed Oct 11 16:38:55 2017 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Oct 11 16:38:55 2017 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Oct 11 16:38:55 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Oct 11 16:38:55 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Oct 11 16:38:55 2017 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Oct 11 16:38:55 2017 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Oct 11 16:38:55 2017 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Oct 11 16:38:55 2017 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Wed Oct 11 16:38:59 2017] ***
compiled with version: 4.8.5 on 10 October 2017 18:13:19
os: Linux-4.4.0-96-generic #119~14.04.1-Ubuntu SMP Wed Sep 13 08:40:48 UTC 2017
nodename: wuh
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/wuh/work/myGit/myPro
detected binary path: /home/wuh/work/myGit/myPro/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/wuh/work/myGit/myPro/app/
your processes number limit is 63767
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
Python version: 2.7.6 (default, Oct 26 2016, 20:33:43)  [GCC 4.8.4]
Set PythonHome to /home/wuh/work/myGit/myPro/venv/
Python main interpreter initialized at 0x195c630
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 702080 bytes (685 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
__init__ is call
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x195c630 pid: 8424 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8424)
spawned uWSGI worker 1 (pid: 8427, cores: 2)
spawned uWSGI worker 2 (pid: 8428, cores: 2)
spawned uWSGI worker 3 (pid: 8429, cores: 2)
spawned uWSGI worker 4 (pid: 8432, cores: 2)
('getJson fileName = ', '../json/bjtq.json')
[pid: 8428|app: 0|req: 1/1] 10.75.109.117 () {50 vars in 847 bytes} [Wed Oct 11 16:39:02 2017] GET / => generated 8684 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
('getJson fileName = ', '../json/bjtq.json')
[pid: 8427|app: 0|req: 1/2] 10.75.109.117 () {48 vars in 812 bytes} [Wed Oct 11 16:39:41 2017] GET / => generated 8684 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 8429|app: 0|req: 1/3] 10.75.109.117 () {48 vars in 790 bytes} [Wed Oct 11 16:39:41 2017] GET /favicon.ico => generated 233 bytes in 6 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 1)
('getJson fileName = ', '../json/bjtq.json')
[pid: 8427|app: 0|req: 2/4] 10.75.80.162 () {46 vars in 936 bytes} [Wed Oct 11 16:40:16 2017] GET / => generated 8684 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
